package org.fd.ase.grp15.ase_conference_service.exception.code;

public enum ConferenceServiceErrorCode {
    ERR_CONFERENCE_NAME_EXISTED,
    ERR_SAME_NAME_CONFERENCE_APPLYING,
    ERR_ILLEGAL_DATE_FORMAT,
    ERR_START_TIME_AFTER_END_TIME,
    ERR_SUBMISSION_TIME_AFTER_RESULT_TIME,
    ERR_ILLEGAL_CONFERENCE_STATUS,
    ERR_CONFERENCE_NAME_NOT_EXISTED,
    ERR_NOT_ADMINISTRATOR,
    ERR_NOT_CHAIR,
    ERR_APPLICATION_STATUS,
    ERR_INTERNAL_SERVER_ERROR,
    ERR_BAD_REQUEST,
}
