spring:
  config:
    import: classpath:application-base.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:13306}/ase_user_service_prod
    username: root
    password: 4iKqWz0dasVpC0z4EQUK
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        
  application:
    name: ase-user-service
  data:
    redis:
      # Redis数据库索引（默认为0）
      database: 10
      # Redis服务器地址
      host: ${REDIS_HOST:127.0.0.1}
      # Redis服务器连接端口
      port: ${REDIS_PORT:6379}
      # Redis服务器连接密码（默认为空）
      password: 5iwrnpFC4BRqADn6qCFV
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
dubbo:
  application:
    name: ase-user-service-dubbo
    qos-port: 22222
    serialize-check-status: WARN
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
    username: nacos
    password: nacos

